### ISSUE TITLE
rx_bytes-r vs rx_bytes

### ISSUE THREAD

**Issue by brian000** [unifi-poller/unifi#33]
I'm trying to create a way to get notified when I'm nearing my ISP's monthly caps, so I'm digging around `unifi-poller`, trying to determine what the difference between `rx_bytes-r` and `rx_bytes` is.

By plugging the two fields into Grafana, I can see that on my setup the `rx_bytes` value is way higher than the `rx_bytes-r` (with the `-r`) value.  Same thing for `tx_bytes`.  Does `-r` denote "realtime" whereas the non-dash-rs are UniFi's value for data-since-last-couter-reset?

**Comment by davidnewhall** [comment]
`rx_bytes-r` is a live rate and `rx_bytes` is accumulated total since the device (or client) came online. The total bytes for the USG WAN port(s) is definitely recorded there, and you could set something up to check the delta for the last ~30 days.

**Comment by davidnewhall** [comment]
You'd have to record the numbers to check the delta. Even recording the "current" total every day at midnight will allow you to find the difference at the end of a 30 day period. UniFi Poller does the recording into Influx or Prometheus; I'll eventually have an "example" mysql output plugin that will allow you do record simple values (like this) to a mysql db.
