### ISSUE TITLE
Docs link on GitHub is wrong

### ISSUE THREAD

**Issue by SamWhited** [unifi-poller/unifi#36]
The website link on GitHub is to https://godoc.org/golift.io/unifi which made me import and try to use that package. It was a while before I noticed that the version was mismatched somehow and that things weren't working that should, then I noticed the readme used the GitHub import path directly and changing to that fixed my project. Please change the documentation link to point at GitHub if this other import path was an old one that's no longer used but still has cached tags that no longer exist or something. Thanks!

**Comment by davidnewhall** [comment]
Whoops! Fixed!

Thanks,
-david
