### ISSUE TITLE
[Feature Request] UDM storage utilization

### ISSUE THREAD

**Issue by buzz-tee** [unifi-poller/unifi#42]
As an administrator I'd like to have a report on storage utilization on my UDM/UDM Pro.
The device object contains this information, please make it available via the poller.

This could be achieved by adding the following entry to UDM struct (https://github.com/unifi-poller/unifi/blob/master/udm.go):
```go
Storage     []struct {
    MountPoint  string  `json:"mount_point"`
    Name        string  `json:"name"`
    Type        string  `json:"type"`
    Size        FlexInt `json:"size"`
    Used        FlexInt `json:"used"`
} `json:"storage"`
```

Thanks and keep up the great work!

**Comment by davidnewhall** [comment]
Sorry, missed this issue. Seems like a good req!

**Comment by davidnewhall** [comment]
Shares the same type as a UXG, so it's also purposeful.

**Comment by davidnewhall** [comment]
I misread this feature request and only added methods to the library. I will get this added to poller soon!

**Comment by davidnewhall** [comment]
This data should be available in the `master` tag now: `docker pull golift/unifi-poller:master` 

If you don't use docker, let me know what platform you're on and I'll attach a dev build for you to try. I have no way to test the changes myself and I appreciate your help!
